document.writeln('   <header>    '); 
document.writeln('           <div class="center-wrap">  '); 
document.writeln('              <div class="companyIdentity">  '); 
document.writeln('                 <a href="index.html"><img src="content-images/yulu-logo.png" alt="" /></a>  '); 
document.writeln('              </div>   '); 
document.writeln('              <!-- END companyIdentity -->  ');                                                                                      
document.writeln('              <!-- START Main Navigation -->  ');   
document.writeln('              <nav>  ');   
document.writeln('                 <ul>  ');   
document.writeln('                    <li class="current-menu-item"><a href="index.html">Home</a></li>  ');   
document.writeln('                     <li>    ');
document.writeln('                  	    <a href="sol_solution.html">Solution</a>   ');
document.writeln('  											<ul class="sub-menu">         ');  
document.writeln('                    			<li><a href="sol_bigdata.html">Big Data</a></li>     ');
document.writeln('                    			<li><a href="sol_blockchain.html">Block Chain</a></li>      ');
document.writeln('                    			<li><a href="sol_ai.html">Artificial Intelligence</a></li>  ');                  
document.writeln('                    			<li><a href="sol_cloud_storage.html">Cloud Storage</a></li>   '); 
document.writeln('                    			<li><a href="sol_cloud_computation.html">Cloud Computing</a></li>  ');
document.writeln('                    			<li><a href="sol_diaster_recovery.html">Disaster Recovery System</a></li>   ');
document.writeln('                    			<li><a href="sol_iot.html">IoT</a></li>   '); 
document.writeln('                    			<li><a href="sol_mppdatabase.html">MPP Database</a></li>             '); 
document.writeln('                    			<li><a href="sol_cloud_search.html">Cloud Search Platform</a></li>    ');
document.writeln('                    			<li><a href="sol_smartcity.html">Smart City Platform</a></li>         ');
document.writeln('                    			<li><a href="sol_carnet.html">Smart Car Networking</a></li>           ');
document.writeln('                    			<li><a href="sol_bigdataui.html">Big Data Application Platform</a></li>    ');
document.writeln('                    			<li><a href="sol_web3.0.html">Web3.0</a></li>   ');
document.writeln('                    			<li><a href="sol_dew_automation.html">DEW Testing Platform</a></li>        ');
document.writeln('                        </ul>  ');   
document.writeln('										</li>  ');       
document.writeln('                     <li>    ');      
document.writeln('                       <a href="service.html">Service Support</a>    ');   
document.writeln('                        <ul class="sub-menu">         ');   
document.writeln('                        	<li><a href="service.html">Business Consulting</a></li>                   ');   
document.writeln('                          <li><a href="service.html">Application Development</a></li>               ');   
document.writeln('                          <li><a href="service.html">Data Migration</a></li>                        ');   
document.writeln('                          <li><a href="service.html">Field Deployment</a></li>                      ');   
document.writeln('                          <li><a href="service.html">Technical Support</a></li>                     ');   
document.writeln('                          <li><a href="service.html">Recovery</a></li>                              ');   
document.writeln('                          <li><a href="certificationtraining.html">Certification and Training</a></li>             ');   
document.writeln('                       </ul>  ');   
document.writeln('                    </li>    ');   
document.writeln('                    <li>     ');   
document.writeln('                       <a href="customercase.html">Case</a>     ');   
document.writeln('                       <ul class="sub-menu">    ');   
document.writeln('                            <li><a href="customercase.html?index=1">Financial</a></li>                      ');   
document.writeln('                            <li><a href="customercase.html?index=2">Agriculture</a></li>                    ');   
document.writeln('                            <li><a href="customercase.html?index=3">Public Security</a></li>                ');   
document.writeln('                            <li><a href="customercase.html?index=4">Civil Aviation</a></li>                 ');   
document.writeln('                            <li><a href="customercase.html?index=5">Environmental Protection</a></li>       ');   
document.writeln('                            <li><a href="customercase.html?index=6">Industry</a></li>                       ');   
document.writeln('                            <li><a href="customercase.html?index=7">Government</a></li>                     ');   
document.writeln('                            <li><a href="customercase.html?index=8">School</a></li>                         ');   
document.writeln('                       </ul>    ');   
document.writeln('                    </li>    ');   
document.writeln('                    <li>     ');   
document.writeln('                       <a>Tech Center</a>   ');   
document.writeln('                       <ul class="sub-menu">    ');   
document.writeln('                            <li><a href="filedownload.html">File Download</a></li>            ');   
document.writeln('                            <li><a href="filedownload.html">Software Download</a></li>     ');
document.writeln('                            <li><a href="DEWcollege.html">DEW College</a></li>                ');   
document.writeln('                            <li><a href="KnowHow.html">Exchange of know-how</a></li>  ');   
document.writeln('                            <li><a href="LeaveMsg.html">DEW Leave Message</a></li>     ');   
document.writeln('                       </ul>   ');   
document.writeln('                    </li>   ');   
document.writeln('                    <li>  ');   
document.writeln('                				<a>More</a>        ');                                                                    
document.writeln('                                  		<ul class="sub-menu">         ');                                            
document.writeln('                                        <li><a href="companyintroduction.html">Company Introduction</a></li>  ');   
document.writeln('                                        <li><a href="founder.html">Introduction of Founder</a></li>      ');   
document.writeln('                                        <li><a href="investment.html">Investment</a></li>    ');   
document.writeln('                                        <li><a href="news.html">News</a></li>    ');   
document.writeln('                                        <li><a href="contact.html">Contact Us</a></li>   ');   
document.writeln('                                        <li><a href="joinus.html">Join Us</a></li>  ');   
document.writeln('                                     </ul>     ');   
document.writeln('                    </li>     ');   
document.writeln('                 </ul>        ');   
document.writeln('              </nav>          ');   
document.writeln('              <!-- END Main Navigation -->      ');   
document.writeln('           </div>         ');   
document.writeln('                             <!-- END center-wrap -->   ');   
document.writeln('                          </header>         ');      


document.writeln('                          <section>         ');          
document.writeln('                          <img src="content-images/banner1.jpg"  style="height:100%;width:100%" >       ');                                                                     
document.writeln('                          </section>	        ');          
        
