document.writeln('     <aside class="top-aside clearfix">   ');
document.writeln('             <div class="center-wrap">  ');
document.writeln('                <div class="one_half">  ');
document.writeln('                   <div class="sidebar-widget"> ');
document.writeln('                      <ul class="custom-menu"> ');
document.writeln('                         <li class="current-menu-item"><a href="../chn/index.html">Chinese</a></li>  ');
document.writeln('                         <li><a href="../eng/sol_solution.html">Solution</a></li>  ');
document.writeln('                         <li><a href="../eng/service.html">Service</a></li>  ');
document.writeln('                         <li><a href="../eng/news.html">News</a></li>   ');
document.writeln('                         <li><a href="../eng/founder.html">Team</a></li>  ');
document.writeln('                         <li><a href="../eng/contact.html">Contact</a></li>  ');
document.writeln('                      </ul>   ');
document.writeln('                   </div>   ');
document.writeln('                </div>  ');
document.writeln('                <!-- END top-toolbar-left -->     ');
document.writeln('                <div class="one_half">    ');
document.writeln('                   <div class="sidebar-widget">  ');
document.writeln('                      <ul class="social_icons">   ');
document.writeln('                         <li><a href="mailto:astronee@microraindrop.com" class="email">Email</a></li> ');
document.writeln('                      </ul>    ');
document.writeln('                   </div>      ');
document.writeln('                                  </div> ');
document.writeln('                                  <!-- END top-toolbar-right -->    ');
document.writeln('                               </div>   ');
document.writeln('                               <!-- END center-wrap -->  ');
document.writeln('                               <div class="top-aside-shadow"></div> ');
document.writeln('        </aside>  ');
